version: '3.8'

services:
  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - server-db

  taxi-redis:
    container_name: taxi-redis
    image: redis:6-alpine

  server-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
      - POSTGRES_DB=taxi
      - POSTGRES_HOST=localhost
volumes:
  postgres_data: